### ISSUE TITLE
Cannot enable votes on comments

### ISSUE THREAD

**Issue by nico01f** [lml/commontator#198]
I have **acts_as_votable** and **commontator** gems, i'm using rails 7.0.0 but doesn't works, and even the comment section it's doesn't show up. Probably a bug? 

Have you ever had this error?
What should I change to make it work?
```
ActionView::Template::Error (missing keywords: :records, :associations):
     8:   can_subscribe = thread.can_subscribe?(user)
     9:   can_edit = thread.can_be_edited_by?(user)
    10:   comments = thread.paginated_comments(page, nil, show_all)
    11:   nested_comments = thread.nested_comments_for(user, comments, show_all)
    12: %>
    13: 
    14: <div id="commontator-thread-<%= thread.id %>-show" class="show commontator-hidden">
  
app/models/commontator/thread.rb:150:in `new'
app/models/commontator/thread.rb:150:in `block in nested_comments_for'
app/models/commontator/thread.rb:147:in `nested_comments_for'
app/views/commontator/threads/_show.html.erb:11
app/views/commontator/threads/_show.js.erb:11
app/views/commontator/threads/show.js.erb:2

```

**Comment by nico01f** [comment]
I didn't notice exist a recent version with the changes. 
This version includes the fixes.

`gem 'commontator', '~> 7.0'`
