### ISSUE TITLE
the commontaor gem is confilicating with active admin for pagenation as active admin uses kaminary but for commontaotr its showing will_paginate

### ISSUE THREAD

**Issue by BBVishalkumar** [lml/commontator#210]
NoMethodError (undefined method `per' for #<ActiveRecord::Relation [#<AdminUser id: 4, email: "vishalkumar@gmail.com", created_at: "2023-08-21 04:56:56.712596000 +0000", updated_at: "2023-08-21 04:56:56.712596000 +0000">, #<AdminUser id: 3, email: "visahlkumar@gmail.com", created_at: "2023-08-21 04:54:11.056354000 +0000", updated_at: "2023-08-21 04:54:11.056354000 +0000">, #<AdminUser id: 2, email: "anuj@bluebash.co", created_at: "2023-07-17 08:19:45.649308000 +0000", updated_at: "2023-08-22 07:46:43.910659000 +0000">, #<AdminUser id: 1, email: "anuj@dentistfind.com", created_at: "2023-07-13 13:08:30.275420000 +0000", updated_at: "2023-08-22 06:35:01.077637000 +0000">]>):
  
activerecord (7.0.7) lib/active_record/relation/delegation.rb:110:in `method_missing'
activeadmin (3.0.0) lib/active_admin/resource_controller/data_access.rb:340:in `paginate'
activeadmin (3.0.0) lib/active_admin/resource_controller/data_acc

**Comment by BBVishalkumar** [comment]
How can override show that its should allow active admin gem to use to kaminary not will_paginate
